name: ci-pr-run
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[A-Z]+-\d+: .+'
          allowed_prefixes: 'IMD,IN,ST,AI,BI'
          prefix_case_sensitive: true
          github_token: ${{ github.token }}
