name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
  workflow_call:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        type: string
        default: 'production'
    secrets:
      DEPLOY_TOKEN:
        required: false

jobs:
  trigger-slave:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Input branch: ${{ inputs.branch }}"
          echo "Input environment: ${{ inputs.environment }}"

      - name: Master Branch Step
        if: inputs.branch == 'master' || inputs.branch == 'main'
        run: echo "This step runs only on master/main branch"

      - name: Non-Master Branch Step
        if: inputs.branch != 'master' && inputs.branch != 'main'
        run: echo "This step runs on non-master branches"

      - name: Trigger Slave Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = {
              branch: '${{ inputs.branch }}',
              environment: '${{ inputs.environment }}',
              sha: context.sha,
              triggered_by: context.actor
            };
            
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'deploy',
              client_payload: payload
            });
